[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.black]
line-length = 80

[tool.poetry.dependencies]
grpcio = "<=1.70.0"
grpcio-tools = "*"
protobuf = "*"
